### ISSUE TITLE
Add the ability to parse Debian copyright text

### ISSUE THREAD

**Issue by nishakm** [nexB/debut#1]
Currently the `DebianCopyright` class can read copyright text from a file. It would be nice to have a similar method to parse copyright text from a python string.

cc @mukultaneja

**Comment by pombredanne** [comment]
@nishakm :wave: ... there you go!

**Comment by pombredanne** [comment]
@nishakm Note that this is partially here and partially in scancode-toolkit at https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/debian_copyright.py as the smarts doing effective license detection on expressions and texts in copyright file paragraphs are in the Toolkit.
There are many refinements needed but this will be tracked in separate tickets: therefore I am closing  this 
Follow up tickets include these here:
- #6 Recover parsing from almost machine-readable copyright files
- #8 Determine the primary license from a copyright file
- https://github.com/nexB/scancode-toolkit/issues/2390 Improve quality and tracing of license detection in Debian copyright files
