### ISSUE TITLE
debut 0.9.8 has requirement chardet<4.0.0,>=3.0.0, but you'll have chardet 4.0.0 which is incompatible

### ISSUE THREAD

**Issue by tdruez** [nexB/debut#5]
This was relaxed in the toolkit: https://github.com/nexB/scancode-toolkit/commit/396805f372c0e8f3ed450f82736a6dd9820fd62e
We should do the same here.

**Comment by pombredanne** [comment]
I pushed a new version 0.9.9 with relaxed upper bound version spec.
Thanks!
